on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  pr-test:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
          - runs-on: windows-11-arm
            arch: win-arm64
          - runs-on: macos-15-intel
            arch: osx-x64
          - runs-on: macos-15
            arch: osx-arm64
          - runs-on: ubuntu-latest
            arch: linux-x64
          - runs-on: ubuntu-24.04-arm
            arch: linux-arm64

    steps:
    - uses: actions/checkout@v1

    - name: pip install
      run: |
        pip install -e .
        pip install pytest

    - name: test
      run: pytest
      working-directory: tests
